# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.24.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
zeros = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
zeros.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
#  python -c "import numpy; help(numpy.nonzero)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
zeros[4]= 1
zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
np.arange(10,50)[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
a = np.array([1,12,0,0,4,0])
np.nonzero(a) # a.nonzero() - both are the same. 


(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.rand(27).reshape((3,3,3))

array([[[0.36840866, 0.28473355, 0.90429648],
        [0.34950794, 0.44644874, 0.91643842],
        [0.72757664, 0.11024429, 0.81778512]],

       [[0.12249254, 0.45303688, 0.08415234],
        [0.02791589, 0.10478992, 0.76181892],
        [0.07509607, 0.67188638, 0.88884018]],

       [[0.07847189, 0.69640857, 0.75874397],
        [0.10160641, 0.81744928, 0.32474486],
        [0.88479004, 0.82929308, 0.58121078]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
a = np.random.randn(100).reshape((10,10))

max = a.max()
min = a.min()
print(max, min)

1.9770525277385158 -2.6317394178896643


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
np.random.rand(30).mean()

0.5128316779605306

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
ones = np.ones(16).reshape((4,4))
ones[1:3,1:3] = 0
ones

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
ones = np.ones(16).reshape((4,4))

ones[0, :] = 0
ones[-1, :] = 0

# Set the first and last columns to 1
ones[:, 0] = 0
ones[:, -1] = 0
ones

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
# 0 * np.nan
# np.nan == np.nan
np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 
3 * 0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
a = np.zeros(25).reshape(5,5)

np.fill_diagonal(a[:,1:],[1,2,3,4])
a

array([[0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.],
       [0., 0., 0., 0., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:

checker_board = np.ones((8,8))
print("Checkerboard pattern:")

checker_board[::2,::2] = 0
checker_board[1::2,1::2] = 0
checker_board

Checkerboard pattern:


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
a = np.arange(1,6*7*8+1).reshape(6,7,8)
np.where(a==100)

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
a = np.array([[0,1], [1,0]])
np.tile(a, (4,4)).reshape(8,8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:

a = np.random.rand(5, 5) *100
print(a)
# Normalize the matrix
a_norm = (a - np.mean(a)) / np.std(a) * 100

print(a_norm)


[[10.5608599  76.15684477 27.21138131 16.45216751 27.670684  ]
 [44.14379379 72.24107633 65.58105297 78.59955152 61.51041124]
 [68.91051752 26.12040656 49.42290079 63.07392068 62.01102277]
 [20.95464995 60.00035167 70.84309741 90.41537258 99.53195175]
 [72.7783386  62.73095535  1.57812963 66.76352518 17.15588366]]
[[-160.61414227   90.61796086  -96.84277696 -138.05048071  -95.08365132]
 [ -31.99177113   75.62059871   50.11276193   99.9735084    34.52223632]
 [  62.86458484 -101.02120166  -11.77283308   40.51046512   36.4395745 ]
 [-120.80600859   28.7387201    70.26635051  145.2280096   180.14443567]
 [  77.67830896   39.19691061 -195.01792813   54.64162116 -135.35525344]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
import numpy as np

# Define a custom dtype for RGBA colors
color_dtype = np.dtype([('r', np.uint8),
                        ('g', np.uint8),
                        ('b', np.uint8),
                        ('a', np.uint8)])

# Create an array of colors
colors = np.array([(255, 0, 0, 255),  # red
                   (0, 255, 0, 255),  # green
                   (0, 0, 255, 255)], # blue
                  dtype=color_dtype)

print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
c = np.dot(a,b) # dot product calculation.
c 

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a = np.arange(10)
a[(a>3)&(a<8)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))

from numpy import *

print(sum(range(5),0))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = 1

print(Z**Z,
2 << Z >> 2,
Z <- Z,
1j*Z,
Z/1/1,
Z<Z>Z)

1 1 False 1j 1.0 False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
np.array([np.nan])

array([nan])

In [29]:
print(np.array(0) / np.array(0),
np.array(0) // np.array(0),
np.array([np.nan]).astype(int).astype(float))

nan 0 [-2.14748365e+09]


C:\Users\ahmet\AppData\Local\Temp\ipykernel_12620\2861961488.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0),
C:\Users\ahmet\AppData\Local\Temp\ipykernel_12620\2861961488.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0),
C:\Users\ahmet\AppData\Local\Temp\ipykernel_12620\2861961488.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
import numpy as np

# Define a float array
x = np.array([-2.3, -1.5, 0.0, 1.5, 2.3])

# Round the array away from zero
rounded = np.sign(x) * np.ceil(np.abs(x) + 1e-15)

print(rounded)

[-3. -2.  0.  2.  3.]


In [31]:
np.ceil(np.abs(0) + 1e-15)

1.0

#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
a = np.array([1,2,3,7,3,6,8,3,34, 11, 23, 34, 10])
b = np.arange(4,14)

np.intersect1d(a,b) # this function brings the common values. 



array([ 6,  7,  8, 10, 11])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
# # Set the error handling behavior to "ignore"
# np.seterr(all='ignore')

# # Your code here...

# # Reset the error handling behavior to its default value
# np.seterr(all='warn')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)


C:\Users\ahmet\AppData\Local\Temp\ipykernel_12620\2961820512.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
today = np.datetime64('today')

yesterday = today - np.timedelta64(1, "D")
tomorrow =  today + np.timedelta64(1, "D")

print(today, yesterday, tomorrow)

2023-03-26 2023-03-25 2023-03-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:

date = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
date.reshape(31)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)
((A+B)*(-A/2))


array([ -2.5,  -7. , -13.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
a = np.random.rand(10) * 10
print(a, np.floor(a))
# np.floor brings the closest integer to the floay. 

print(a, np.ceil(a)-1)

print(a, np.round(a)) # this rounds up to the closest integer after the . of the float. 

print(a, np.trunc(a))

[5.10747661 8.0466809  6.25728112 2.43831002 0.06325621 1.13665661
 6.02216443 1.32848825 6.36669885 2.19268321] [5. 8. 6. 2. 0. 1. 6. 1. 6. 2.]
[5.10747661 8.0466809  6.25728112 2.43831002 0.06325621 1.13665661
 6.02216443 1.32848825 6.36669885 2.19268321] [5. 8. 6. 2. 0. 1. 6. 1. 6. 2.]
[5.10747661 8.0466809  6.25728112 2.43831002 0.06325621 1.13665661
 6.02216443 1.32848825 6.36669885 2.19268321] [5. 8. 6. 2. 0. 1. 6. 1. 6. 2.]
[5.10747661 8.0466809  6.25728112 2.43831002 0.06325621 1.13665661
 6.02216443 1.32848825 6.36669885 2.19268321] [5. 8. 6. 2. 0. 1. 6. 1. 6. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
a = np.tile(np.arange(5),(5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def my_generator():
    for i in range(10):
        yield i

# Use numpy.fromiter() to build an array from the generator
arr = np.fromiter(my_generator(), dtype=int)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
a = np.random.rand(10)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
a.sort()
a

array([0.02068973, 0.15746353, 0.35363966, 0.42112059, 0.44530525,
       0.47616432, 0.53111546, 0.56768343, 0.84598057, 0.89392963])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
from numpy.core._methods import _sum # special function for faster sum. 

# Create a small array of integers
arr = np.array([1, 2, 3, 4, 5])

# Use numpy.core._methods._sum() to sum the array faster than np.sum()
result = _sum(arr)

print(result)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
equality = np.array_equal(a,b)
print(a,
b,
equality)

[0.02068973 0.15746353 0.35363966 0.42112059 0.44530525 0.47616432
 0.53111546 0.56768343 0.84598057 0.89392963] [ 4  5  6  7  8  9 10 11 12 13] False


#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
# b.flags.writeable = False

# b[1] = 0

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
cartesian_coords = np.random.rand(10, 2)

# Convert the cartesian coordinates to polar coordinates
r = np.sqrt(cartesian_coords[:, 0]**2 + cartesian_coords[:, 1]**2)
theta = np.arctan2(cartesian_coords[:, 1], cartesian_coords[:, 0])

# Combine the r and theta values into a 10x2 matrix of polar coordinates
polar_coords = np.column_stack((r, theta))

print(polar_coords)

[[0.3569547  0.21039759]
 [0.30109482 0.79150938]
 [1.24170668 0.81537173]
 [0.56278288 0.37181264]
 [0.03115491 0.44966846]
 [0.277157   1.11163553]
 [0.7825558  0.58201751]
 [0.31826287 0.51030319]
 [0.71043631 1.04939206]
 [0.99834311 1.20467272]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
a = np.random.rand(5)*10
print(a)
a[(np.where(a == a.max()))] = 0
print(a, "\n")

vec = np.random.rand(5) *10
print(vec)
# Replace the maximum value in the vector with 0
vec[np.argmax(vec)] = 0 

print(vec)


[7.25366043 3.58005548 9.03923987 2.72232608 9.81890915]
[7.25366043 3.58005548 9.03923987 2.72232608 0.        ] 

[6.54197516 6.04443921 5.22371029 7.72653461 9.04843662]
[6.54197516 6.04443921 5.22371029 7.72653461 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [48]:
nx, ny = (5,5)

# Generate a grid of x and y values using numpy.meshgrid()
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(yv)
# Create a structured array with x and y coordinates as fields
coords = np.rec.fromarrays([xv, yv], names=('x', 'y'))


# print(coords)

[[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)