In [1]:
import numpy as np
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [3]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d[0,2]

15

In [4]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [5]:
import numpy as np
arr=np.arange(1,37)
arr.shape

(36,)

In [6]:
import pandas as pd
import numpy as np

In [9]:
data = [(1,2,3), 
(10,20,30), 
(100,200,300)]
labels = ('A', 'B', 'C')
pd.DataFrame(data, index=['I', 'J', 'K'], columns=labels)

A    B    C
I    1    2    3
J   10   20   30
K  100  200  300

In [15]:
data = {'A':[1,10,100],
        'B':[2,20,200],
        'C':[3,30,300]}

pd.DataFrame(data) # this will create a dataframe using the keys as colums names and allocate the values. items will be iterated

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]], dtype=int64)

In [17]:
pd.DataFrame(data).values # returns array

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]], dtype=int64)

In [16]:
pd.DataFrame(data).head

<bound method NDFrame.head of      A    B    C
0    1    2    3
1   10   20   30
2  100  200  300>

In [19]:
pd.DataFrame(data).shape

(3, 3)

In [20]:
pd.DataFrame(data).size

9

In [21]:
pd.DataFrame(data).ndim

2

In [22]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
c

array([5, 7, 9])