___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright Pierian Data</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# NumPy Exercises

#### 1. Import NumPy as np

In [2]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [15]:
# CODE HERE

zeros  = '0 ' * 10
zeros_list = zeros.split()
zeros_list = [float(i) for i in zeros_list]
new_arr = np.array(zeros_list)
new_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
# DON'T WRITE HERE

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [16]:
# CODE HERE
np_ones = np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# DON'T WRITE HERE

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [17]:
# CODE HERE
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
# DON'T WRITE HERE

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create an array of the integers from 10 to 50

In [19]:
# CODE HERE

np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# DON'T WRITE HERE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

In [20]:
# CODE HERE

np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# DON'T WRITE HERE

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
# CODE HERE

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# DON'T WRITE HERE

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix

In [25]:
# CODE HERE

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# DON'T WRITE HERE

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [26]:
# CODE HERE

np.random.random()

0.7566399013378144

In [9]:
# DON'T WRITE HERE

array([0.65248055])

In [28]:
np.random.randn(10,10)

array([[ 1.32868758,  0.69351786,  0.40850479,  0.70371326, -1.62726153,
         0.95024062,  0.11561486, -0.83986197,  0.20609644,  3.09540716],
       [ 0.07940146, -1.41532703,  0.34798106, -0.01996397, -0.45159082,
        -1.15399048, -1.5130075 ,  0.28933716,  0.35469592, -0.24476311],
       [ 0.50713392, -0.83603289, -0.04294095, -1.16036178,  1.06197003,
         0.32918765, -0.47968243,  0.63077893, -0.78938818, -1.22836579],
       [ 2.7383134 , -1.52612597, -0.47182427,  1.12892203, -0.30443952,
        -1.02506677,  0.2184725 ,  1.28945899,  0.47588504, -0.23968777],
       [ 0.2426414 ,  1.41038224,  0.81724829, -0.62777829, -1.44425767,
         1.19073194,  0.47309333, -1.65511722, -0.60492445, -0.67742211],
       [ 0.81705736,  0.07707811,  0.20253122, -0.83531853, -0.07149392,
         0.81769028, -0.06066565, -1.2024124 ,  1.68747912, -0.95266804],
       [-0.75857461, -1.04013795, -2.37381843, -0.6905184 ,  0.91252393,
        -0.91723642, -0.12975681,  0.38650004

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [29]:
# CODE HERE

np.random.randn(25)

array([ 0.10157946, -1.15469699,  0.09813454, -0.02211698, -0.63122036,
       -0.14583878,  0.78201023,  1.26655559,  1.75063298,  1.37409751,
       -0.16119905, -1.41208024,  0.17446657,  0.36339546, -1.33786994,
        0.50776336,  0.72601594, -0.43672011,  0.79652331, -2.12006229,
        0.67284286,  1.03575202,  0.56833685,  1.199871  , -0.18649175])

In [10]:
# DON'T WRITE HERE

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Create the following matrix:

In [31]:
# CODE HERE

np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
# DON'T WRITE HERE

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [33]:
# CODE HERE

np.linspace(0,1, num=20) #.linespace(start,stop, num=) allows us to create evenly spaced arrays. 

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# DON'T WRITE HERE

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [34]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [35]:
# CODE HERE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# DON'T WRITE HERE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code that reproduces the output shown below.

In [37]:
# CODE HERE

mat[3,4]

20

In [15]:
# DON'T WRITE HERE

20

#### 15. Write code that reproduces the output shown below.

In [39]:
# CODE HERE
mat[0:3, [1]] # if we use the square brackets for columns, we add a dimension. 

array([[ 2],
       [ 7],
       [12]])

In [16]:
# DON'T WRITE HERE

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that reproduces the output shown below.

In [42]:
# CODE HERE
mat[-1]


array([21, 22, 23, 24, 25])

In [17]:
# DON'T WRITE HERE

array([21, 22, 23, 24, 25])

#### 17. Write code that reproduces the output shown below.

In [43]:
# CODE HERE
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# DON'T WRITE HERE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. Get the sum of all the values in mat

In [44]:
# CODE HERE

mat.sum() # sums up all the elements in the array and brings the result. 

325

In [19]:
# DON'T WRITE HERE

325

#### 19. Get the standard deviation of the values in mat

In [45]:
# CODE HERE

mat.std() # standard deviation of the array's elements


7.211102550927978

In [20]:
# DON'T WRITE HERE

7.211102550927978

#### 20. Get the sum of all the columns in mat

In [50]:
# CODE HERE
print(mat.sum(axis=0)) #this is the sum of all columns.
mat.sum(axis=1) #this is the sum of all rows.


[55 60 65 70 75]


array([ 15,  40,  65,  90, 115])

In [21]:
# DON'T WRITE HERE

array([55, 60, 65, 70, 75])

## Bonus Question

We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [70]:
np.random.seed(42) # random.seed gives the same random numbers everytime it is called. 
np.random.randn(40)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
        1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,
        0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
       -0.60170661,  1.85227818, -0.01349722, -1.05771093,  0.82254491,
       -1.22084365,  0.2088636 , -1.95967012, -1.32818605,  0.19686124])

In [75]:
np.random.randn(40)

array([ 0.35778736,  0.56078453,  1.08305124,  1.05380205, -1.37766937,
       -0.93782504,  0.51503527,  0.51378595,  0.51504769,  3.85273149,
        0.57089051,  1.13556564,  0.95400176,  0.65139125, -0.31526924,
        0.75896922, -0.77282521, -0.23681861, -0.48536355,  0.08187414,
        2.31465857, -1.86726519,  0.68626019, -1.61271587, -0.47193187,
        1.0889506 ,  0.06428002, -1.07774478, -0.71530371,  0.67959775,
       -0.73036663,  0.21645859,  0.04557184, -0.65160035,  2.14394409,
        0.63391902, -2.02514259,  0.18645431, -0.66178646,  0.85243333])

# Great Job!